name:                hai
version:             0.1.0.0
github:              "Enzo-Liu/hai"
license:             BSD3
author:              "Enzo Liu"
maintainer:          "liuenze6516@gmail.com"
copyright:           "Copyright: (c) 2016 Enzo Liu"

extra-source-files:
- README.org
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            personal

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Enzo-Liu/hai#readme>

dependencies:
- base >= 4.7 && < 5
- qtah-qt5
- binary >=0.7 && <0.9
- bytestring >=0.10 && <0.11
- containers <0.6
- filepath >=1.0 && <1.5
- hoppy-runtime >=0.5 && <0.6
- random

library:
  source-dirs: src

executables:
  hai-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -dynamic
    dependencies:
    - hai

tests:
  hai-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -dynamic
    dependencies:
    - hai
